Change database extension name
Makeroid/TinyWebDB-PHP pull request #4
Opened 2019-06-07 08:26 UTC by ColinTree

2019-06-16 17:12 UTC, barreeeiroo requested changes

2019-06-16 17:12 UTC, barreeeiroo commented on getvalue.php
> +    rename("data.txt", $file);
I think this is wrong

```suggestion
    rename("database.json", $file);
```

2019-06-16 17:12 UTC, barreeeiroo commented on storeavalue.php
> +    rename("data.txt", $file);
I think this is wrong too

```suggestion
    rename("database.json", $file);
```

2019-06-16 22:20 UTC, ColinTree commented
Fixed an typo

2019-06-17 11:43 UTC, barreeeiroo approved these changes

2019-06-17 11:43 UTC, merged